<<<<<<< HEAD
---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "SinglePaged - Simple Jekyll template"
keywords:    "SinglePaged, jekyll, template, github, blog, single page"
description: "A single-page template for Jekyll based blogs (like what you'd use on github pages!)"
source_link: "https://github.com/t413/SinglePaged"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

=======
# Site settings
name: Nick Chitwood
description: "District testing overlord, (barely) recovering former HS band teacher, and funder of 4 college funds."
url: "http://www.nickchitwood.com"


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  nickchitwood
# codepen_username: your_codepen_username_goes_here
facebook_username: nicholas.chitwood
# vk_username: your_vk_username_goes_here
twitter_username: nickchitwood
# google_plus_username: your_google_plus_username_goes_here
linkedin_username: nicholaschitwood
#vine_username:  your_vine_username_goes_here
#instagram_username:  your_instagram_username_goes_here
#flickr_username: your_flickr_username_goes_here
#steam_username: your_steam_username_goes_here
#soundcloud_username:  your_soundcloud_username_goes_here
#stack_of_username: your_stack_overflow_account_id_number_goes_here
#reddit_username: your_reddit_username_goes_here
#medium_username:  your_medium_username_goes_here
#tumblr_username: your_tumblr_username_goes_here
#weibo_username: your_weibo_username_goes_here
#lastfm_username: your_lastfm_username_goes_here
blog_url: "/blog"
email: nicholaschitwood@gmail.com
#public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars0.githubusercontent.com/u/9169546"


front_img: yes
front_img_path: "imgs/sandsmall.jpg"
#front_img_path: "https://github.com/nickchitwood/nickchitwood.github.io/blob/master/imgs/sandsmall.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
>>>>>>> parent of 850597e... Update for Apple repair
